// Map props: set dressing that is ALSO collision (players and bullets stop at
// it), so the Blender models and the server never disagree. Each prop kind
// expands into a few AABBs here; art/blender/build_maps.py models the visual
// (drums, bags, pallets, arches…) over the same footprint.
//
// Placement data per map lives in props-data.js, generated by
// tools/place-props.mjs (deterministic, validated against the nav graph).

export const PROP_KINDS = {
  barrel:   { size: [28, 44, 28], mat: 'metal' },     // oil drum
  barrels:  { size: [58, 44, 30], mat: 'metal' },     // two drums side by side
  sandbags: { size: [112, 40, 34], mat: 'bags' },     // chest-high sandbag wall
  pallets:  { size: [52, 34, 52], mat: 'wood' },      // stacked pallets + sacks
  planter:  { size: [34, 30, 34], mat: 'stone' },     // clay pot with a shrub
  awning:   { size: [120, 10, 56], mat: 'cloth', y: 104 }, // cloth canopy over a door
};

// rot: 0 or 90 (degrees about Y). Returns [{min, max, mat}].
export function propColliders(p) {
  if (p.kind === 'arch') return archColliders(p);
  const k = PROP_KINDS[p.kind];
  if (!k) return [];
  let [sx, sy, sz] = k.size;
  if (p.rot === 90) [sx, sz] = [sz, sx];
  const y0 = p.pos[1] + (k.y || 0);
  return [{
    min: [p.pos[0] - sx / 2, y0, p.pos[2] - sz / 2],
    max: [p.pos[0] + sx / 2, y0 + sy, p.pos[2] + sz / 2],
    mat: k.mat,
  }];
}

// Stone arch over a doorway: a lintel spanning the gap, high enough to walk
// and jump under, plus two pilasters proud of the wall ends.
// { kind:'arch', pos:[cx, y, cz], axis:'x'|'z' (wall direction), span, thick, top }
export function archColliders(p) {
  const { pos: [cx, y, cz], axis, span, thick, top } = p;
  const out = [];
  const lintel = [span + 32, 40, thick + 8];
  const pil = [16, top - y, thick + 12];
  const put = (ox, oy, s) => {
    const [a, b] = axis === 'x' ? [s[0], s[2]] : [s[2], s[0]];
    const px = axis === 'x' ? cx + ox : cx;
    const pz = axis === 'x' ? cz : cz + ox;
    out.push({ min: [px - a / 2, oy, pz - b / 2], max: [px + a / 2, oy + s[1], pz + b / 2], mat: 'arch' });
  };
  put(0, top - 40, lintel);
  put(-(span / 2 + 8), y, pil);
  put(span / 2 + 8, y, pil);
  return out;
}
